using DestallMaterials.CodeGeneration;
using DestallMaterials.WheelProtection.Extensions.Objects;
using DestallMaterials.WheelProtection.Linq;
using System.Xml.Serialization;

namespace CodeGenerationTests;

[Parallelizable(scope: ParallelScope.All)]
[TestFixture]
public class FileAddingTests : CodeGenerationTests
{
    [Test]
    public async Task AddFile_Existing_ShouldNotAdd()
    {
        // Arrange
        var system = CodeGenerationWorkspace.Create(_consumerProject, SourceFilesWritingSettings.NameAnnotated);
        var projectName = system.ProjectLocations.Keys.First(pn => pn.Contains("Consumer"));
        string[] folders = ["FolderedItems"];
        ProjectRelativeFilePath path = new(projectName, folders, "FolderedClass.cs");
        var sourceFile = new CodeFile(path, sourceText);

        // Act
        var added = await system.AddSourceFilesAsync([sourceFile], default);
        
        // Assert
        Assert.IsEmpty(added);
    }

    [Test]
    public async Task AddFile_New_ShouldAdd()
    {
        // Arrange
        var system = CodeGenerationWorkspace.Create(_consumerProject);
        var projectName = system.ProjectLocations.Keys.First(pn => pn.Contains("Consumer"));

        // Act
        var sourceFile = new CodeFile(new ProjectRelativeFilePath(projectName, "ConsumerModel2.cs"), sourceText);
        var added = await system.AddSourceFilesAsync(sourceFile.Yield(), default);

        // Assert
        Assert.IsNotEmpty(added);
    }

    [Test]
    public async Task AddFile_New_NextDifferent_ShouldAdd_AndOverwrite()
    {
        // Arrange
        var system = CodeGenerationWorkspace.Create(_consumerProject, SourceFilesWritingSettings.NameAnnotated);
        var projectName = system.ProjectLocations.Keys.First(pn => pn.Contains("Consumer"));
        string[] folders = ("Folder1", "Folder2", "LastFolder").ToArray();

        // Act
        var sourceFile = new CodeFile(new ProjectRelativeFilePath(projectName, folders, "ConsumerModel2.cs"), sourceText);
        var added1 = await system.AddSourceFileAsync(sourceFile, default);
        var added2 = await system.AddSourceFileAsync(sourceFile, default);
        var added3 = await system.AddSourceFileAsync(sourceFile with { Content = sourceText + sourceText }, default);

        // Assert
        Assert.IsTrue(added1);
        Assert.IsFalse(added2);
        Assert.IsTrue(added3);
    }

    [Test]
    public void ChangeFileName_AutogeneratedNotation_MustNotAffectRazorFiles()
    {
        CodeFile input = new(new("Proj", "input.razor"), "");

        var annotated = input.WithAutogeneratedContentMark();

        Assert.AreEqual(annotated.Path, input.Path);
    }

    [Test]
    public void ChangeFileName_AutogeneratedNotation_MustAddAutogeneratedNotation()
    {
        const string input = "input.cs";

        var annotated = SourceFilesWritingSettings.WithAutogeneratedAnnotation(input);

        Assert.IsTrue(annotated.EndsWith("g.cs"));
    }
}